MODEL_UNET = "Unet"
MODEL_MOBILE_RES_UNET = "MobileResUNet"

DATASET_MNIST = "MNIST"
DATASET_CIFAR10 = "CIFAR10"

LOSS_L2 = "L2"
LOSS_LPIPS_HUBER = "LPIPS_HUBER"

DATA_DIR = "./data"
EXPERIMENTS_DIR = "experiments"

# UNet
UNET_DIM = 64
UNET_DIM_MULTS = (1, 2, 4, 8)
SINUSOIDAL_POS_EMB_THETA = 10000

# MobileResUNet
TIME_EMB_DIM = 32
NUM_GROUPS = 4

# FID
FID_EPS = 1e-6
INCEPTION_V3_INPUT_SIZE = (299, 299)
